# Generated by Django 2.2 on 2021-05-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BtcData',
            fields=[
                ('date', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('var', models.FloatField()),
            ],
        ),
    ]
