# Generated by Django 2.2 on 2021-06-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_proyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagenDestacada',
            field=models.FileField(default='Descripcion', upload_to='imgproyectos'),
        ),
    ]
