# Generated by Django 2.2 on 2021-06-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210602_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion_corta',
            field=models.CharField(blank=True, default='Descripcion Corta', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagenDestacada',
            field=models.FileField(blank=True, null=True, upload_to='imgproyectos'),
        ),
    ]
