# Generated by Django 2.2 on 2021-06-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210602_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='url',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
