# Generated by Django 2.2 on 2021-06-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_proyecto_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='url',
            field=models.CharField(blank=True, default=models.CharField(max_length=250), max_length=50, null=True),
        ),
    ]
