# Generated by Django 2.2 on 2021-06-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210602_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='url',
            field=models.CharField(blank=True, default='Descripcion Corta', max_length=50, null=True),
        ),
    ]
